name: terminice
description: "A library for creating and managing terminal interfaces."
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^6.0.0
