name: terminice_workspace
description: Terminice Workspace
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

workspace:
  - terminice_core
  - terminice_components
  - terminice

dependencies:

dev_dependencies:
  test: ^1.26.1
  lints: ^6.0.0
