name: terminice
description: "The best and easiest way to build terminal-based applications in Dart. With 30+ prompts and viewers, beautiful themes, and ease of use."
version: 0.0.12
homepage: https://github.com/jozzdart/terminice
repository: https://github.com/jozzdart/terminice/tree/main/terminice
issue_tracker: https://github.com/jozzdart/terminice/issues
documentation: https://github.com/jozzdart/terminice/tree/main/terminice#readme
topics:
  - terminal
  - cli
  - prompt
  - terminal-interface
  - terminal-ui

environment:
  sdk: ">=2.17.0 <4.0.0"

platforms:
  linux:
  macos:
  windows:

dependencies:
  terminice_core: ^0.0.9
  intl: ^0.20.0
  time_plus: ^1.3.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
