name: terminice_core
description: "Core functionality for Terminice."
resolution: workspace
version: 0.0.3
homepage: https://github.com/jozzdart/terminice
repository: https://github.com/jozzdart/terminice/tree/main/terminice_core
issue_tracker: https://github.com/jozzdart/terminice/issues
topics:
  - terminal
  - cli
  - prompt
  - terminal-interface
  - terminal-ui

environment:
  sdk: ">=3.5.0 <4.0.0"

platforms:
  linux:
  macos:
  windows:

dependencies:

dev_dependencies:
  lints:
